name: "ðŸŒ¸ Linting"

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd backend && npm install --frozen-lockfile
      - run: cd backend && npm run check-format
      - run: cd backend && npm run lint
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd frontend && npm install --frozen-lockfile
      - run: cd frontend && npm run check-format
      - run: cd frontend && npm run lint
